# Generated by Django 4.1.5 on 2023-01-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaApp.author')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaApp.editor')),
                ('genre', models.ManyToManyField(to='mangaApp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('cover', models.ImageField(upload_to='tomes/')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('file', models.FileField(upload_to='chapters/')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaApp.series')),
                ('tome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaApp.tome')),
            ],
        ),
    ]
